name: Compile
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:samd:mkrvidor4000'
