# This is a basic workflow to help you get started with Actions

name: Compile
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:samd:mkrvidor4000

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
